### ISSUE TITLE
MQTT5 specific attributes

### ISSUE THREAD

**Issue by alexandrim0** [emqx/emqx-rule-engine#119]
Hi!

The Rule Engine is amazing and powerfull part of EMQX. But it would be nice to be able to select MQTT5 specific attributes by it`s name or all of them by *.
Are you planning to do feature like that?

Thank you!

**Comment by tigercl** [comment]
Hi, @alexandrim0.
Thank you for your suggestion. We will discuss it and let you know if there is any progress.

**Comment by alexandrim0** [comment]
Hello!

Is there any progress in discussion?

**Comment by HJianBo** [comment]
@alexandrim0 Thanks for your suggestion.

Can you give me some detailed attributes example that you wanted

**Comment by alexandrim0** [comment]
Mostly I need this:
Response Topic \ Correlation Data \ Response Information
Payload format Indicators \ Content Types
User Properties

Also would be great to be able to process cbor body not only json.
With that features EMQX turns from broker to App Server.

Thank you!

**Comment by alexandrim0** [comment]
Any news or plans?

**Comment by HJianBo** [comment]
@alexandrim0 Sorry It may need some days

**Comment by HJianBo** [comment]
Hi, @alexandrim0 We have implemented it has released it in the v4.2-alpha.1.
