### ISSUE TITLE
$events/message_published

### ISSUE THREAD

**Issue by kozelok** [emqx/emqx-rule-engine#146]
Is it possible to make an _optimized_ $events/message_published available via config with a topic pattern filter/username filter/clientid filter? 

Its a great alternative for the fan-in pattern where I'm essentially ingesting a ton of messages and extracting the FROM:CLIENTID, FROM:USERNAME  via topic pattern.

**Comment by terry-xiaoyu** [comment]
For emqx v4.0+, there's no such event topic `$events/message_published`, all the events we have is listed in [emqx_rule_engine.conf](https://github.com/emqx/emqx-rule-engine/blob/a9706513b802aa948eeb104cd2f3880b5ef6ee94/etc/emqx_rule_engine.conf#L21)

For publish messages you can write the SQL match against the topic if your topics contain the clientid or username info, e.g.

```
select * from "client/+"
```

Or you have no clientid info in your topics:

```
select * from "#" where clientid = '123' and username = 'abc'
```

Here the clientid and username is the clientid/username of the publisher.
