### ISSUE TITLE
Bad Arguments Error

### ISSUE THREAD

**Issue by beraybentesen** [emqx/emqx-rule-engine#147]
While creating a new rule through the REST API, the body I am sending is :

`{
  "name": "test",
  "for": "data_to_webserver",
  "rawsql": "SELECT payload.Temperature as temp, clientid as device_id FROM e03719f2-f13b-416a-97b7-d0a93ae8ae3c WHERE temp < 10",
  "actions": [
    {
      "name": "Google Cloud Functions Email Alert",
      "params": {
        "$resource": "resource:1b3f75d5"
      }
    }
  ],
  "description": "test"
}`

**Comment by terry-xiaoyu** [comment]
@beraybentesen The correct format of the SQL is (emqx 4.0.0+):

```
SELECT <fields> from "<topic>"
```

See the documents for usages, English version will come soon: 

[Rule API](https://docs.emqx.io/broker/latest/cn/advanced/http-api.html#endpoint-rules)

[Rule engine docs](https://docs.emqx.io/broker/latest/cn/advanced/rule-engine.html)

**Comment by beraybentesen** [comment]
@terry-xiaoyu Thank you that fixed. English example would be great since it does not contain response examples.
