### ISSUE TITLE
Message batch processing available?

### ISSUE THREAD

**Issue by yongchen77** [emqx/emqx-rule-engine#179]
When create a rule with event like SELECT * FROM "t/#", message is sent to action handler one by one. Is it possible to put them to a message pool, e.g. SELECT * FROM "t/#" of last 1 second , then event is triggered each second, and all messages published in the last second are all put to the message pool as an array, and send to actions? Another example is SELECT BATCH 100 * FROM "t/#", then when matched messages is added up to 100, send to actions. Save a batch  to db is more efficient then one by one.

**Comment by terry-xiaoyu** [comment]
Currently the rule engine cannot do any stream processing, I may be added in the next minor/major version but I am not sure.

**Comment by terry-xiaoyu** [comment]
We may add some simple window processing functions such as `BATCH` or `SUM` in emqx_rule_engine.
For more complicated scenarios, a specific stream processing product `HStream` is under development.

**Comment by yongchen77** [comment]
Thanks.
