### ISSUE TITLE
Rules not persistent

### ISSUE THREAD

**Issue by nishant-vvdn** [emqx/emqx-rule-engine#225]
After creating rules in emqx broker, when the pod restarted the rules were deleted. Have to create rules again for the Kubernetes deployment pod.

**Comment by HJianBo** [comment]
Rules are persistent. But only if you mount the `data/` directory for each node.

**Comment by nishant-vvdn** [comment]
Can you please elaborate a bit on how to do that? Because I can't seem to implement this properly.

Or if there's any way to create client_disconnected rule via emqx_ctl in EMQ X Broker.

**Comment by Rory-Z** [comment]
Hi，@nishant-vvdn
You can use our helm chart to deploy emqx on k8s, and helm chart provides persistence options, as you can see here: https://github.com/emqx/emqx-rel/tree/master/deploy/charts/emqx

**Comment by nishant-vvdn** [comment]
Thank you, @zhanghongtong 
I will look into it.

**Comment by nishant-vvdn** [comment]
Hi @HJianBo @zhanghongtong 
Is there a way to create a rule for the event client_disconnected in terminal? 

Because, **emqx_ctl rules create "SELECT * FROM \"$events/client_disconnected\"" '[{"name":"republish", "params":{"payload_tmpl":"{\"client\": ${clientid}}", "target_qos":1, "target_topic":"device/status/inward"}}]'** 

this doesn't seem to work.

**Comment by wwhai** [comment]
> Hi @HJianBo @zhanghongtong
> Is there a way to create a rule for the event client_disconnected in terminal?
> 
> Because, **emqx_ctl rules create "SELECT * FROM "$events/client_disconnected"" '[{"name":"republish", "params":{"payload_tmpl":"{"client": ${clientid}}", "target_qos":1, "target_topic":"device/status/inward"}}]'**
> 
> this doesn't seem to work.

Please check your config:
```sh
> emqx_ctl  rules create "SELECT * FROM "$events/client_disconnected"" '[{"name":"republish", "params":{"payload_tmpl":"{"client": ${clientid}}", "target_qos":1, "target_topic":"device/status/inward"}}]'
RPC to emqx@127.0.0.1 error: {51,invalid_json}
```
you can try this demo:
```sh
bin/emqx_ctl  rules create 'SELECT * FROM "$events/client_disconnected"' '[{"name":"republish","params":{"target_topic":"repub/to/${clientid}","target_qos":0,"payload_tmpl":"${payload}"},"fallbacks":[]}]'
```

**Comment by nishant-vvdn** [comment]
![emqx_rule](https://user-images.githubusercontent.com/77484178/105820161-336c1880-5fdf-11eb-9611-0edddb240829.png)

My rule seem to work but as you can see that rule has been created.

**Comment by nishant-vvdn** [comment]
![image](https://user-images.githubusercontent.com/77484178/105820401-86de6680-5fdf-11eb-89ff-6e96479bef64.png)

But still the rule is not appearing correctly in EMQX UI.

**Comment by nishant-vvdn** [comment]
@wwhai your query seem to be working. Was it because your SQL Syntax was in single quotes?

**Comment by wwhai** [comment]
> @wwhai your query seem to be working. Was it because your SQL Syntax was in single quotes?

It's no different between two symbols, maybe `\` be added in SQL.

**Comment by terry-xiaoyu** [comment]
It must be the string `$events` was treated as an SHELL variable.

**Comment by nishant-vvdn** [comment]
@terry-xiaoyu  must be it.

**Comment by zbertj** [comment]
> 
> 
> Rules are persistent. But only if you mount the `data/` directory for each node.

The rule disappeared after restarting EMQX and I had mounted the `data/` directory. i used docker-compose,

**Comment by nishant-vvdn** [comment]
@terry-xiaoyu  @HJianBo  @Rory-Z  @wwhai  when using kubernetes statefulset on local machine, rules are persisting because same docker IP is being assigned to the emqx node, for example **/opt/emqx/data/mnesia/emqx@172.17.0.9**

But when I'm using aks (azure kubernetes) to deploy EMQX on aks cluster using azure files, node IP is different everytime. For example if **/opt/emqx/data/mnesia/emqx@10.1.1.10** is assigned to the EMQX node, then if I try to delete the pod then **/opt/emqx/data/mnesia/emqx@10.1.1.11** might be assigned to it.

so, nothing is persisting.

**Comment by HJianBo** [comment]
In azure kubernetes, is it possible to guarantee that the IP is fixed once the node is up and running? Because in the current version, emqx persistence is dependent on the name of the node.

Alternatively, you can fix the node name with the environment variable (EMQX_NODE__NAME) when you start the node. see: https://hub.docker.com/r/emqx/emqx

**Comment by zmstone** [comment]
A better approach is perhaps not to use IP address for the node names.
but with a private network created and assign host names to the containers.

I have not tried azure, with **only** docker installed, you can do it like the script below:
The highlighted lines are some explanation on why to create a network.
https://github.com/emqx/emqx/blob/aadd1ba11a3e0de2e162afe8b6c2d9184f78ff02/scripts/start-two-nodes-in-docker.sh#L13-L16
