### ISSUE TITLE
How to create a rule

### ISSUE THREAD

**Issue by biswaKL** [emqx/emqx-rule-engine#7]
Hi, I have installed the raspberry pi version of emqx and is it possible to create a rule there, and also i want to know if we can save the rules in mongodb instead of sql

**Comment by Gilbert-Wong** [comment]
Not now, sorry @biswaKL , we'll implement this feature in enterprise edition of emqx.

**Comment by zhengyupan** [comment]
@biswaKL Thank you for being interested in the rule engine feature. This feature is still under development, we haven't completely ready to release this feature, and in which edition should this feature be delivered is still under discussion.   
More details will follow as the development goes.

**Comment by biswaKL** [comment]
Ok guys thanks a lot for the update...
